[program:eveskinserver]
directory=/home/eveskinserver
command=/home/eveskinserver/venv/bin/gunicorn --bind 0.0.0.0:8000 eveskinserver.app:app
user=eveskinserver
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/eveskinserver/eveskinserver.err.log
stdout_logfile=/var/log/eveskinserver/evesskinserver.out.log
